puppycompanyblog/models.py
from puppycompanyblog import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    profile_image = db.Column(db.String(64), nullable=False, default='default_profile.png')
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    posts = db.relationship('BlogPost', backref='author', lazy=True)

    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.set_password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'Username {self.username}'


class BlogPost(db.Model):
    pass

puppycompanyblog/__init__.py
# puppycompanyblog/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)

###############################################################
##### DATABASE SETUP #################################
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app, db)
##############################################


###############################################################
##### LOGIN CONFIGS #################################
login_manager = LoginManager()

login_manager.init_app(app)
login_manager.login_view = 'users.login'
##############################################


from puppycompanyblog.core.views import core
from puppycompanyblog.error_pages.handlers import error_pages

app.register_blueprint(core)
app.register_blueprint(error_pages)

puppycompanyblog/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)


@core.route('/')
def index():
    return render_template('index.html')


@core.route('/info')
def info():
    return render_template('info.html')

puppycompanyblog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../static/pico-1.5.10/css/pico.css">
    <title>Document</title>
</head>
<body>

<nav class="container">
    <ul>
        <li><strong>Puppy Company Blog</strong></li>
    </ul>
    <ul>
        <li><a href="{{ url_for('core.index') }}">Home</a></li>
        <li><a href="{{ url_for('core.info') }}">About</a></li>
        <li><a href="{{ url_for('core.info') }}">Log Out</a></li>
        <li><a href="{{ url_for('core.info') }}">Account</a></li>
        <li><a href="{{ url_for('core.info') }}">Create Post</a></li>
        <li><a href="{{ url_for('core.info') }}">Log In</a></li>
        <li><a href="{{ url_for('core.info') }}">Register</a></li>
    </ul>
</nav>

<main class="container">
    {% block content %}

    {% endblock %}
</main>

</body>
</html>

puppycompanyblog/templates/index.html
{% extends 'base.html' %}

{% block content  %}
    <article>
        <h1>Puppy Company Blog</h1>
    </article>
{% endblock %}

puppycompanyblog/templates/info.html
{% extends 'base.html' %}

{% block content %}
    <article>
            <h1>Info about our company</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium at beatae corporis delectus
                doloremque eaque esse expedita fuga id maxime nisi nobis, odio pariatur quisquam saepe sequi
                voluptatibus! Ipsa, iste.</p>
    </article>
{% endblock %}